config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  root to: 'pages#home'
  get 'pages/home'

resources :songs

  # get "songs" => "songs#index"
  # get 'songs/new' => "songs#new", as: :new_song
  # get "songs/:id" => "songs#show", as: :song
  # post "songs" => "songs#create"
  # get 'songs/:id/edit' => 'songs#edit', as: :edit_song
  # patch "songs/:id" => "songs#update"
  # delete "songs/:id" => "songs#destroy"
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :song
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  def self.order_by_name
  order(:music_genre)
  end
  belongs_to :artist, dependent: :destroy
  has_many :photos

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:music_genre)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
   @songs = Song.all
  end
  def show
  @song = Song.find(params[:id])
  end
  def new
    @song = Song.new
  end
  def create
  song_params = params.require(:song).permit(:music_genre, :producer_name, :image_url)

  @song = song.new(song_params)

  if @song.save
     redirect_to @song
  else
     render 'new'
  end
  end
  def edit
    @song = Song.find(params[:id])
  end
  def update
    @song = song.find(params[:id])

    song_params = params.require(:song).permit(:name, :age, :image_url)

  if @song.update_attributes(song_params)
      redirect_to @song
  else
      render 'edit'
  end
  end
  def destroy
 @song = Song.find(params[:id])

 @song.destroy

 redirect_to songs_path
  end

  private

  def song_params
   params.require(:song).permit(:music_genre, :producer_name, :image_url, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.music_genre %>
</p>

<h4>List of Singers</h4>

<% if @valley.songs.any? %>
  <ul>
    <% @valley.songs.each do |dino| %>
      <li><%= singer.music_genre %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no singers in this artist.</p>
<% end %>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

    <br><br>
    <hr>
    <%= link_to "[All Songs]", root_path %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurbnb2", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>

 <ul>
   <% @song.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
 </ul>
  <%= f.label :music_genre %>
  <%= f.text_field :music_genre %>

  <%= f.label :producer_name %>
  <%= f.text_field :producer_name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit (@song.new_record? ? "Create" : "Update") %>

  <%= f.label :artist_id %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :music_genre) %>

<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
  <p><%= song.music_genre %></p>
  <p><%= link_to song.music_genre, song_path(song.id) %></p>

<% end %>
<hr>

<%= link_to "[New Song]", new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render "form" %>
<%= form_for @song do |f| %>
  <%= f.label :music_genre %>
  <%= f.text_field :music_genre %>

  <%= f.label :producer_name %>
  <%= f.text_field :producer_name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit "Create" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.music_genre %></h1>

<p>Producer_name: <%= @song.producer_name %></p>
<%= image_tag @song.image_url %>
<hr>

<%= link_to "[Edit]", edit_song_path(@song.id) %>

<%= link_to "[Delete]", song_path(@song.id), method: :delete, data: { confirm: "Are you sure?" } %>

<h4>Photos</h4>
<% @song.photos.each do |photo| %>
  <%= image_tag photo.image %>
<% end %>